### ISSUE TITLE
Be able to automate the python interpreter

### ISSUE THREAD

**Issue by thisdougb** [thisdougb/typetastic#47]
Be able to do this:

```
config:
    prompt-string: "$ "
    typing-color: bright-green
    typing-speed: supersonic

commands:
    - python3 --version
    - python3:
        - python3
        - import secrets
        - secrets.token_hex(16)
        - CTRL_D
    - whoami
```
